apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: web
spec:
  containers:
  - name: myctn
    image: nginx
    resources:
      requests:
        cpu: 200m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 64Mi
    ports:
      - containerPort: 80
    volumeMounts:
      - name: myvol1
        mountPath: /usr/share/nginx/html
  volumes:
    - name: myvol1
      persistentVolumeClaim:
        claimName: dev-pvc