server:
  servlet:
    context-path: /notice

spring:
  config:
    import: 'aws-secretsmanager:rds!db-9a9aeb30-99f3-4615-a349-0335d291d4a1'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://notice-db.cdkk8ekkyyy8.ap-northeast-2.rds.amazonaws.com:3306/notice?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: ${username}
    password: ${password}

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


services-url:
  central: ""